// TNS (TOS Name Service) Transaction Test Vector Generator (Type 21)
// Generates test vectors for cross-language verification between TOS Rust and Avatar C
//
// Transaction Types:
//   Type 21: RegisterName - Register a human-readable name (e.g., alice@tos.network)

use hex;
use serde::Serialize;
use std::fs::File;
use std::io::Write;
use tos_common::serializer::Serializer;
use tos_common::transaction::RegisterNamePayload;

// ============================================================================
// YAML Structures
// ============================================================================

#[derive(Serialize)]
struct TnsTestVectors {
    algorithm: String,
    version: u32,
    register_name_vectors: Vec<RegisterNameVector>,
}

#[derive(Serialize)]
struct RegisterNameVector {
    name: String,
    description: String,
    tns_name: String,
    wire_hex: String,
    expected_size: usize,
}

// ============================================================================
// Vector Generation
// ============================================================================

fn gen_register_name_vectors() -> Vec<RegisterNameVector> {
    let mut vectors = Vec::new();

    // Basic name (5 chars)
    {
        let tns_name = "alice".to_string();
        let payload = RegisterNamePayload::new(tns_name.clone());
        let wire = payload.to_bytes();

        vectors.push(RegisterNameVector {
            name: "register_name_basic".to_string(),
            description: "Register basic 5-char name".to_string(),
            tns_name,
            wire_hex: hex::encode(&wire),
            expected_size: wire.len(),
        });
    }

    // Minimum length name (3 chars)
    {
        let tns_name = "bob".to_string();
        let payload = RegisterNamePayload::new(tns_name.clone());
        let wire = payload.to_bytes();

        vectors.push(RegisterNameVector {
            name: "register_name_min".to_string(),
            description: "Register minimum length (3 char) name".to_string(),
            tns_name,
            wire_hex: hex::encode(&wire),
            expected_size: wire.len(),
        });
    }

    // Longer name (16 chars)
    {
        let tns_name = "cryptoenthusiast".to_string();
        let payload = RegisterNamePayload::new(tns_name.clone());
        let wire = payload.to_bytes();

        vectors.push(RegisterNameVector {
            name: "register_name_16chars".to_string(),
            description: "Register 16-char name".to_string(),
            tns_name,
            wire_hex: hex::encode(&wire),
            expected_size: wire.len(),
        });
    }

    // Name with numbers
    {
        let tns_name = "user123".to_string();
        let payload = RegisterNamePayload::new(tns_name.clone());
        let wire = payload.to_bytes();

        vectors.push(RegisterNameVector {
            name: "register_name_alphanumeric".to_string(),
            description: "Register alphanumeric name".to_string(),
            tns_name,
            wire_hex: hex::encode(&wire),
            expected_size: wire.len(),
        });
    }

    // Name with underscore
    {
        let tns_name = "my_wallet".to_string();
        let payload = RegisterNamePayload::new(tns_name.clone());
        let wire = payload.to_bytes();

        vectors.push(RegisterNameVector {
            name: "register_name_underscore".to_string(),
            description: "Register name with underscore".to_string(),
            tns_name,
            wire_hex: hex::encode(&wire),
            expected_size: wire.len(),
        });
    }

    vectors
}

// ============================================================================
// Main
// ============================================================================

fn main() {
    let vectors = TnsTestVectors {
        algorithm: "TNS-Transactions".to_string(),
        version: 1,
        register_name_vectors: gen_register_name_vectors(),
    };

    let yaml = serde_yaml::to_string(&vectors).expect("Failed to serialize to YAML");

    // Add header comment
    let header = r#"# TNS (TOS Name Service) Transactions Test Vectors (Type 21)
# Generated by TOS Rust - gen_tns_vectors
# Cross-language verification between TOS Rust and Avatar C
#
# Transaction Types:
#   Type 21: RegisterName - Register a human-readable name (e.g., alice@tos.network)
#
# RegisterName Wire Format:
#   [name_len:1][name:1-64]

"#;

    let output = format!("{}{}", header, yaml);

    // Write to file
    let output_path = "tns.yaml";
    let mut file = File::create(output_path).expect("Failed to create output file");
    file.write_all(output.as_bytes())
        .expect("Failed to write output");

    println!("Generated TNS vectors to {}", output_path);
    println!("  RegisterName: {}", vectors.register_name_vectors.len());
}
