"""TOS Python spec configuration constants.

Keep this file aligned with Rust constants in `common/src/transaction/*` and
`common/src/transaction/verify/*`.
"""

# Transaction limits
EXTRA_DATA_LIMIT_SIZE = 128
EXTRA_DATA_LIMIT_SUM_SIZE = EXTRA_DATA_LIMIT_SIZE * 32  # 4KB
MAX_TRANSFER_COUNT = 500
MAX_DEPOSIT_PER_INVOKE_CALL = 255
MAX_MULTISIG_PARTICIPANTS = 255
MAX_NONCE_GAP = 64
MAX_DELEGATEES = 500

# Energy / freeze
MIN_FREEZE_TOS_AMOUNT = 1  # in whole TOS units (spec-level; actual base unit in code)
MIN_UNFREEZE_TOS_AMOUNT = 1

# Privacy
MIN_SHIELD_TOS_AMOUNT = 100  # TOS

# TNS
MIN_NAME_LENGTH = 3
MAX_NAME_LENGTH = 64
MIN_TTL = 100
MAX_TTL = 86_400
MAX_ENCRYPTED_SIZE = 188

# Arbitration / Escrow / KYC placeholders
MIN_ARBITER_STAKE = 0  # TODO: fill from config
MAX_ARBITER_NAME_LEN = 128
MAX_FEE_BPS = 10_000
MAX_TASK_ID_LEN = 256
MAX_REASON_LEN = 1024
MAX_REFUND_REASON_LEN = 1024
MIN_TIMEOUT_BLOCKS = 10
MAX_TIMEOUT_BLOCKS = 525_600
MIN_APPEAL_DEPOSIT_BPS = 500
MAX_BPS = 10_000

MAX_COMMITTEE_MEMBERS = 21
MIN_COMMITTEE_MEMBERS = 3
MAX_APPROVALS = 15
EMERGENCY_SUSPEND_MIN_APPROVALS = 2
MAX_COMMITTEE_NAME_LEN = 128
MAX_MEMBER_NAME_LEN = 64

# Contract limits
MAX_VALUE_CELL_DEPTH = 64
MAX_ARRAY_SIZE = 10_000
MAX_MAP_SIZE = 10_000
MAX_BYTES_SIZE = 1_000_000
MAX_EVENTS_PER_TX = 1000
MAX_ERROR_RETURN_DATA = 4096

# Chain / network
CHAIN_ID_MAINNET = 0
CHAIN_ID_TESTNET = 1
CHAIN_ID_STAGENET = 2
CHAIN_ID_DEVNET = 3
