"""Daemon error codes mapping (from tck/specs/error-codes.md and daemon/src/core/error.rs)."""
from __future__ import annotations
from dataclasses import dataclass
from typing import List, Optional

RPC_ERROR_BASE = 200

@dataclass(frozen=True)
class DaemonErrorSpec:
    name: str
    description: Optional[str]
    discriminant: int

    def rpc_code(self) -> int:
        return RPC_ERROR_BASE + self.discriminant

def rpc_code_from_discriminant(discriminant: int) -> int:
    return RPC_ERROR_BASE + discriminant

def get_error(name: str) -> Optional[DaemonErrorSpec]:
    return next((err for err in ERRORS if err.name == name), None)

ERRORS: List[DaemonErrorSpec] = [
    DaemonErrorSpec("InvalidConfig", "Invalid configuration provided", 0),
    DaemonErrorSpec("CorruptedData", "Invalid data on disk: corrupted", 1),
    DaemonErrorSpec("NoContractBalance", "No contract balance found", 2),
    DaemonErrorSpec("ContractAlreadyExists", "Contract already exists", 3),
    DaemonErrorSpec("ContractNotFound", "Contract not found: {}", 4),
    DaemonErrorSpec("InvalidTipsOrder", "Invalid tip order for block {}, expected {}, got {}", 5),
    DaemonErrorSpec("CommitPointAlreadyStarted", "commit point already started", 6),
    DaemonErrorSpec("CommitPointNotStarted", "commit point not started", 7),
    DaemonErrorSpec("NoMultisig", "no multisig found", 8),
    DaemonErrorSpec("VersionedNotFound", "Versioned data not found in disk", 9),
    DaemonErrorSpec("BlockNotOrdered", "Block is not ordered", 10),
    DaemonErrorSpec("InvalidBalancesMerkleHash", "Invalid balances merkle hash for block {}, expected {}, got {}", 11),
    DaemonErrorSpec("InvalidTipsMerkleHash", "Invalid tips merkle hash for block {}, expected {}, got {}", 12),
    DaemonErrorSpec("TxTooBig", "Transaction size is {} while limit is {}", 13),
    DaemonErrorSpec("TimestampIsLessThanParent", "Timestamp {} is less than parent", 14),
    DaemonErrorSpec("TimestampIsInFuture", "Timestamp {} is greater than current time {}", 15),
    DaemonErrorSpec("InvalidBlockHeight", "Block height mismatch, expected {}, got {}.", 16),
    DaemonErrorSpec("BlockHeightZeroNotAllowed", "Block height is zero which is not allowed", 17),
    DaemonErrorSpec("InvalidBlockHeightStableHeight", "Block height is in stable height which is not allowed", 18),
    DaemonErrorSpec("InvalidDifficulty", "Invalid difficulty", 19),
    DaemonErrorSpec("TxNonceAlreadyUsed", "Tx nonce {} already used by Tx {}", 20),
    DaemonErrorSpec("InvalidHash", "Invalid hash, expected {}, got {}", 21),
    DaemonErrorSpec("InvalidPreviousBlockHash", "Invalid previous block hash, expected {}, got {}", 22),
    DaemonErrorSpec("InvalidBlockSize", "Block size is more than limit, expected maximum: {}, got {}", 23),
    DaemonErrorSpec("InvalidBlockTxs", "Block contains invalid txs count: expected {}, got {} txs.", 24),
    DaemonErrorSpec("InvalidTxInBlock", "Block contains an unknown tx: {}", 25),
    DaemonErrorSpec("TxNotFound", "Tx {} not found in mempool", 26),
    DaemonErrorSpec("TxNotFoundInSortedList", "Tx {} was present in mempool but not in sorted list!", 27),
    DaemonErrorSpec("TxAlreadyInMempool", "Tx {} already in mempool", 28),
    DaemonErrorSpec("TxEmpty", "Normal Tx {} is empty", 29),
    DaemonErrorSpec("InvalidReferenceHash", "Transaction has an invalid reference: block hash not found", 30),
    DaemonErrorSpec("InvalidReferenceTopoheight", "Transaction has an invalid reference: topoheight {0} is higher than our topoheight {1}", 31),
    DaemonErrorSpec("NoPreviousBalanceFound", "No previous balance found", 32),
    DaemonErrorSpec("NoStableReferenceFound", "Transaction has an invalid reference: no balance version found in stable chain", 33),
    DaemonErrorSpec("TxAlreadyInBlock", "Tx {} is already in block", 34),
    DaemonErrorSpec("InvalidTxFee", "Invalid Tx fee, expected at least {}, got {}", 35),
    DaemonErrorSpec("FeesToLowToOverride", "Fees are lower for this TX than the overrided TX, expected at least {}, got {}", 36),
    DaemonErrorSpec("AccountNotFound", "No account found for {}", 37),
    DaemonErrorSpec("InvalidTransactionNonce", "Invalid transaction nonce: {}, account nonce is: {}", 38),
    DaemonErrorSpec("InvalidTransactionToSender", "Invalid transaction, sender trying to send coins to himself: {}", 39),
    DaemonErrorSpec("InvalidTransactionExtraData", "Invalid extra data in this transaction", 40),
    DaemonErrorSpec("InvalidTransferExtraData", "Invalid extra data in transfer", 41),
    DaemonErrorSpec("InvalidNetwork", "Invalid network state", 42),
    DaemonErrorSpec("BlockNotFound", "Error while retrieving block by hash: {} not found", 43),
    DaemonErrorSpec("BlockHeightNotFound", "Error while retrieving block by height: {} not found", 44),
    DaemonErrorSpec("LowerCumulativeDifficulty", "Chain has a too low cumulative difficulty", 45),
    DaemonErrorSpec("NoCumulativeDifficulty", "No cumulative difficulty found", 46),
    DaemonErrorSpec("ErrorStd", None, 47),
    DaemonErrorSpec("ErrorOnBech32", None, 48),
    DaemonErrorSpec("ErrorOnP2p", None, 49),
    DaemonErrorSpec("ErrorOnReader", None, 50),
    DaemonErrorSpec("ErrorOnPrompt", None, 51),
    DaemonErrorSpec("PoisonError", "Poison Error: {}", 52),
    DaemonErrorSpec("IsSyncing", "Blockchain is syncing", 53),
    DaemonErrorSpec("InvalidTransactionSignature", "Invalid transaction signature", 54),
    DaemonErrorSpec("GenesisBlockMiner", "Genesis block is not mined by dev address!", 55),
    DaemonErrorSpec("InvalidGenesisBlock", "Invalid genesis block", 56),
    DaemonErrorSpec("NotEnoughBlocks", "Not enough blocks", 57),
    DaemonErrorSpec("Unknown", "Unknown data store error", 58),
    DaemonErrorSpec("NoTxSignature", "No signature found for this TX", 59),
    DaemonErrorSpec("SmartContractTodo", "Smart Contract not supported yet", 60),
    DaemonErrorSpec("UnexpectedTransactionVariant", "Unexpected transaction variant to set fees", 61),
    DaemonErrorSpec("DatabaseError", "Unexpected error on database: {}", 62),
    DaemonErrorSpec("UnsupportedOperation", "Unsupported operation", 63),
    DaemonErrorSpec("NotFoundOnDisk", "Data not found on disk: {}", 64),
    DaemonErrorSpec("ConfigSyncMode", "Invalid config sync mode", 65),
    DaemonErrorSpec("ExpectedTips", "Expected at least one tips", 66),
    DaemonErrorSpec("InvalidTipsCount", "Block {0} has invalid tips count: {1}", 67),
    DaemonErrorSpec("InvalidTipsNotFound", "Block {0} has an invalid tip {1} which is not present in chain", 68),
    DaemonErrorSpec("InvalidTipsDifficulty", "Block {0} has invalid tips difficulty: {1}", 69),
    DaemonErrorSpec("InvalidBlockVersion", "Invalid block version", 70),
    DaemonErrorSpec("MissingVrfData", "Block {0} missing VRF data", 71),
    DaemonErrorSpec("InvalidVrfData", "Block {0} has invalid VRF data: {1}", 72),
    DaemonErrorSpec("InvalidTxVersion", "Invalid tx version", 73),
    DaemonErrorSpec("AlreadyInChain", "Block is already in chain", 74),
    DaemonErrorSpec("InvalidReachability", "Block has an invalid reachability", 75),
    DaemonErrorSpec("BlockDeviation", "Block has too much deviated", 76),
    DaemonErrorSpec("InvalidGenesisHash", "Invalid genesis block hash", 77),
    DaemonErrorSpec("InvalidTxNonce", "Invalid tx {} nonce (got {} expected {}) for {}", 78),
    DaemonErrorSpec("InvalidTxNonceMempoolCache", "Invalid tx nonce {} for mempool cache, range: [{}-{}]", 79),
    DaemonErrorSpec("AssetNotFound", "Invalid asset ID: {}", 80),
    DaemonErrorSpec("DifficultyError", None, 81),
    DaemonErrorSpec("NoBalance", "No balance found on disk for {}", 82),
    DaemonErrorSpec("NoBalanceChanges", "No balance changes for {} at topoheight {} and asset {}", 83),
    DaemonErrorSpec("NoNonce", "No nonce found on disk for {}", 84),
    DaemonErrorSpec("Overflow", "Overflow detected", 85),
    DaemonErrorSpec("BalanceOverflow", "Balance overflow detected - would exceed u64::MAX", 86),
    DaemonErrorSpec("DeadTxFromStableHeight", "Error, block {} include a dead tx {} from stable height {} executed in block {}", 87),
    DaemonErrorSpec("DeadTxFromTips", "Error, block {} include a dead tx from tips {}", 88),
    DaemonErrorSpec("TxAlreadyInBlockchain", "TX {} is already in blockchain", 89),
    DaemonErrorSpec("PruneHeightTooHigh", "Cannot prune, not enough blocks", 90),
    DaemonErrorSpec("PruneZero", "Cannot prune until topoheight 0, provide a positive number", 91),
    DaemonErrorSpec("PruneLowerThanLastPruned", "Prune topoheight is lower or equal than previous pruned topoheight", 92),
    DaemonErrorSpec("AutoPruneMode", "Auto prune mode is misconfigured", 93),
    DaemonErrorSpec("TryFromSliceError", None, 94),
    DaemonErrorSpec("InvalidCiphertext", "Invalid ciphertext", 95),
    DaemonErrorSpec("NoSenderOutput", "Invalid chain state, no sender output ?", 96),
    DaemonErrorSpec("NoTxSender", "Invalid chain state, sender {} account is not found", 97),
    DaemonErrorSpec("DecompressionError", None, 98),
    DaemonErrorSpec("Any", None, 99),
    DaemonErrorSpec("InvalidNonce", "Invalid nonce for TX {}: expected {}, got {}", 100),
    DaemonErrorSpec("SenderIsReceiver", "Sender cannot be receiver", 101),
    DaemonErrorSpec("TransactionProof", "Invalid transaction proof: {}", 102),
    DaemonErrorSpec("POWHashError", "Error while generating pow hash", 103),
    DaemonErrorSpec("TransferCount", "Transfer count is invalid", 104),
    DaemonErrorSpec("Commitments", "Invalid commitments assets", 105),
    DaemonErrorSpec("MultiSigNotConfigured", "MultiSig is not configured", 106),
    DaemonErrorSpec("MultiSigParticipants", "Invalid multisig participants count", 107),
    DaemonErrorSpec("MultiSigThreshold", "Invalid multisig threshold", 108),
    DaemonErrorSpec("InvalidTransactionFormat", "Invalid transaction format", 109),
    DaemonErrorSpec("InvalidInvokeContract", "Invalid invoke contract", 110),
    DaemonErrorSpec("DepositNotFound", "Deposit not found", 111),
    DaemonErrorSpec("MultiSigNotFound", "MultiSig not found", 112),
    DaemonErrorSpec("ModuleError", "Error in module: {}", 113),
    DaemonErrorSpec("InvalidTransactionMultiThread", "Invalid transaction in block while verifying in multi-thread mode", 114),
    DaemonErrorSpec("UnknownAccount", "Unknown account", 115),
    DaemonErrorSpec("SemaphoreError", None, 116),
    DaemonErrorSpec("ReferralAlreadyBound", "User has already bound a referrer", 117),
    DaemonErrorSpec("ReferralSelfReferral", "Cannot set self as referrer", 118),
    DaemonErrorSpec("ReferralCircularReference", "Circular reference detected in referral chain", 119),
    DaemonErrorSpec("ReferralRatiosTooHigh", "Total reward ratio exceeds 100%", 120),
    DaemonErrorSpec("ReferralReferrerNotFound", "Referrer not found", 121),
    DaemonErrorSpec("ReferralRecordNotFound", "Referral record not found", 122),
    DaemonErrorSpec("NotImplemented", "Feature not implemented", 123),
    DaemonErrorSpec("KycNotFound", "KYC record not found", 124),
    DaemonErrorSpec("KycAlreadySet", "KYC already set for this user", 125),
    DaemonErrorSpec("InvalidKycLevel", "KYC level is invalid", 126),
    DaemonErrorSpec("KycExpired", "KYC has expired", 127),
    DaemonErrorSpec("KycRevoked", "KYC is revoked", 128),
    DaemonErrorSpec("KycSuspended", "KYC is suspended", 129),
    DaemonErrorSpec("InsufficientKycLevel", "Insufficient KYC level: required {0}, got {1}", 130),
    DaemonErrorSpec("KycDowngradeNotAllowed", "KYC level downgrade not allowed: current level {0}, attempted level {1}", 131),
    DaemonErrorSpec("KycLevelExceedsCommitteeMax", "KYC level exceeds destination committee's max level", 132),
    DaemonErrorSpec("CommitteeNotFound", "Committee not found", 133),
    DaemonErrorSpec("CommitteeAlreadyExists", "Committee already exists", 134),
    DaemonErrorSpec("GlobalCommitteeAlreadyExists", "Global Committee already exists", 135),
    DaemonErrorSpec("GlobalCommitteeNotBootstrapped", "Global Committee not bootstrapped", 136),
    DaemonErrorSpec("ParentCommitteeNotFound", "Parent committee not found", 137),
    DaemonErrorSpec("InvalidMaxKycLevel", "Invalid max KYC level for committee", 138),
    DaemonErrorSpec("MemberNotFound", "Member not found in committee", 139),
    DaemonErrorSpec("MemberAlreadyExists", "Member already exists in committee", 140),
    DaemonErrorSpec("CannotRemoveLastMember", "Cannot remove last member from committee", 141),
    DaemonErrorSpec("InsufficientApprovals", "Insufficient approvals for operation", 142),
    DaemonErrorSpec("CommitteeNotActive", "Committee is not active", 143),
    DaemonErrorSpec("InvalidCommitteeThreshold", "Invalid committee threshold", 144),
    DaemonErrorSpec("CommitteeHasChildren", "Cannot delete committee with active children", 145),
    DaemonErrorSpec("UnoNotImplemented", "UNO (privacy balance) not implemented yet", 146),
    DaemonErrorSpec("TnsNameAlreadyRegistered", "TNS name is already registered", 147),
    DaemonErrorSpec("TnsAccountAlreadyHasName", "Account already has a registered name", 148),
    DaemonErrorSpec("TnsNameNotFound", "TNS name not found", 149),
    DaemonErrorSpec("TnsMessageIdAlreadyUsed", "Message ID already used (replay attack)", 150),
    DaemonErrorSpec("TnsSenderNotNameOwner", "Sender does not own the name", 151),
    DaemonErrorSpec("TnsRecipientNotRegistered", "Recipient name not registered", 152),
    DaemonErrorSpec("TnsInvalidTtl", "Invalid TTL value", 153),
    DaemonErrorSpec("TnsMessageTooLarge", "Message content too large", 154),
    DaemonErrorSpec("TnsInvalidNameFormat", "Invalid name format", 155),
    DaemonErrorSpec("TnsNameReserved", "Name is reserved", 156),
    DaemonErrorSpec("InvalidPublicKey", "Invalid compressed public key", 157),
    DaemonErrorSpec("Storage", None, 158),
]
